### ISSUE TITLE
Крашы

### ISSUE THREAD

**Issue by Chernobl** [alexgorovenko/bestGameEver#20]
Несколько раз игра просто зависла. Я не мог никуда тыкнуть. 
Первый раз с обстрелом, он просто зациклился и ход не передавался, и никто не атакавал.
Второй раз когда был фул стол (все фланги забиты) он просто отказался передавать ходы.
Третий раз с оглушение и обстрелом, они несколько раз начали сменять друг друга в кнопки и всё, всё зациклилось

**Comment by zhuravlev12** [comment]
fixed
