### ISSUE TITLE
Атака. Проблема выбора.

### ISSUE THREAD

**Issue by Chernobl** [alexgorovenko/bestGameEver#29]
Стало лучше. Но выбор атакующего нельзя отменить, например. Кроме того, бывает, как будто они сами атакуют, хотя я не кликал на них (может быть это клик в защите засчитался)

**Comment by Chernobl** [comment]
Защита и атака до сих пор нормально не работают. Хотя и стало лучше.

**Comment by zhuravlev12** [comment]
fixed
