### ISSUE TITLE
Выход по esc

### ISSUE THREAD

**Issue by StanislavTrenin** [alexgorovenko/bestGameEver#3]
1) Попап выхода отрывается сразу при запуске игры
2) При открытом попапе остальной экран остаётся активным
3) Попап появлятся в нижней части экрана, видно только вопрос, кнопок не видно

**Comment by Chernobl** [comment]
В экран не влизает
![image](https://user-images.githubusercontent.com/60459261/73517879-6234ca80-442f-11ea-9e1e-8cb38cbc5aaa.png)
