### ISSUE TITLE
Дрожь земли наносит только 1 челику урон

### ISSUE THREAD

**Issue by Chernobl** [alexgorovenko/bestGameEver#37]
![image](https://user-images.githubusercontent.com/60459261/73640029-20f72180-46a0-11ea-81ec-13b921e3bdd8.png)

**Comment by Chernobl** [comment]
Вот так было перед использованием
![image](https://user-images.githubusercontent.com/60459261/73640064-353b1e80-46a0-11ea-90e7-4eb4847219e5.png)

**Comment by zhuravlev12** [comment]
not a bug
