### ISSUE TITLE
Сброс

### ISSUE THREAD

**Issue by StanislavTrenin** [alexgorovenko/bestGameEver#5]
Да, список карт сброса открывается, но при этом не блокируется остальной экран и непонятно как го закрыть

**Comment by StanislavTrenin** [comment]
Короче он выглядеть должен так:
1) Слева снизу тёмная карта с черепком(нарисует Андрей)
2) Пр нажатии на него открывается попап со всеми картами в сбросе (мб со скроллером, если их много). Снизу попапа кнопка закрыть.

**Comment by zhuravlev12** [comment]
fixed
